class UserModel {
  String? nationalId;
  String? address;
  String? husbandName;
  int? socialStatus;
  int? personalStatus;
  String? birthDate;
  String? phone;
  String? working;
  int? healthStatus;
  int? childrenNumber;
  int? housing;
  int? owning;
  UserModel(
      {required this.nationalId,
      required this.address,
      required this.husbandName,
      required this.socialStatus,
      required this.personalStatus,
      required this.birthDate,
      required this.phone,
      required this.working,
      required this.healthStatus,
      required this.childrenNumber,
      required this.housing,
      required this.owning});
}

List<UserModel> usersList = [
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
  UserModel(
      nationalId: '112312321',
      address: 'شارع ١٢ القطعه ٤',
      husbandName: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: 1,
      owning: 1),
];
