
import 'dart:convert';

class UserModel {
  UserModel({
    this.nationalId,
    this.address,
    this.husbandId,
    this.socialStatus,
    this.personalStatus,
    this.birthDate,
    this.phone,
    this.working,
    this.healthStatus,
    this.childrenNumber,
    this.housing,
    this.parentId,
    this.owning,
  });

  final int? nationalId;
  final String? address;
  final String? husbandId;
  final String? parentId;
  final int? socialStatus;
  final int? personalStatus;
  final String? birthDate;
  final String? phone;
  final String? working;
  final int? healthStatus;
  final int? childrenNumber;
  final String? housing;
  final String? owning;

  factory UserModel.fromRawJson(String str) =>
      UserModel.fromJson(json.decode(str));

  String toRawJson() => json.encode(toJson());

  factory UserModel.fromJson(Map<String, dynamic> json) => UserModel(
        nationalId: json["nationalId"],
        address: json["address"],
        parentId: json["parentId"],
        husbandId: json["husbandId"],
        socialStatus: json["socialStatus"],
        personalStatus: json["personalStatus"],
        birthDate: json["birthDate"],
        phone: json["phone"],
        working: json["working"],
        healthStatus: json["healthStatus"],
        childrenNumber: json["childrenNumber"],
        housing: json["housing"],
        owning: json["owning"],
      );

  Map<String, dynamic> toJson() => {
        "nationalId": nationalId,
        "address": address,
        "parentId": parentId,
        "husbandId": husbandId,
        "socialStatus": socialStatus,
        "personalStatus": personalStatus,
        "birthDate": birthDate,
        "phone": phone,
        "working": working,
        "healthStatus": healthStatus,
        "childrenNumber": childrenNumber,
        "housing": housing,
        "owning": owning,
      };
}

List<UserModel> usersList = [
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserModel(
      nationalId: 112312321,
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
];
