class UserEntity {
  UserEntity({
    this.nationalId,
    this.address,
    this.husbandId,
    this.socialStatus,
    this.personalStatus,
    this.birthDate,
    this.phone,
    this.working,
    this.healthStatus,
    this.childrenNumber,
    this.housing,
    this.parentId,
    this.name,
    this.owning,
  });

  String? nationalId;
  String? address;
  String? name;
  String? husbandId;
  String? parentId;
  int? socialStatus;
  int? personalStatus;
  String? birthDate;
  String? phone;
  String? working;
  int? healthStatus;
  int? childrenNumber;
  String? housing;
  String? owning;
}

List<UserEntity> usersList = [
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
  UserEntity(
      nationalId: "112312321",
      address: 'شارع ١٢ القطعه ٤',
      husbandId: 'ثناء عادل محمد',
      socialStatus: 1,
      personalStatus: 1,
      birthDate: '22/12/2020',
      phone: '01115922250',
      working: 'رئيس قسم البنتجان',
      healthStatus: 1,
      childrenNumber: 1,
      housing: "شفه",
      owning: "شفه"),
];
