name: Build and Release APK
on:
  push:
    branches:
      - 'main'
jobs:
    hosting:
      name: Deploy Website
      runs-on: ubuntu-latest
      steps:
        # Checkout Repository
        - uses: actions/checkout@v1

        # Install Flutter command
        - uses: subosito/flutter-action@v1
          with:
            channel: 'dev'

        # Build Website
        - name: Build Website
          run: |
            flutter config --enable-web
            flutter pub get
            flutter build web --release --no-sound-null-safety
          working-directory: ./

        # Deploy Firebase Hosting
        - name: Deploy Firebase Hosting
          uses: w9jds/firebase-action@master
          with:
            args: deploy --only hosting:test-fire-dart
          env:
            FIREBASE_TOKEN: 1//03jNgYFy0WrmACgYIARAAGAMSNwF-L9IrpDilO4CNzozCtRb1VbCEy45tLiJeijwvKi2qlXT3v6BLpbFyydGHEuNHlpb1-nAtuH0
            PROJECT_PATH: ./
